INSERT INTO BREWER.PERMISSAO VALUES(1,'ROLE_CADASTRAR_CIDADE');
INSERT INTO BREWER.PERMISSAO VALUES(2,'ROLE_CADASTRAR_USUARIO');

INSERT INTO BREWER.GRUPO_PERMISSAO (CODIGO_GRUPO,CODIGO_PERMISSAO) VALUES(1,1);
INSERT INTO BREWER.GRUPO_PERMISSAO (CODIGO_GRUPO,CODIGO_PERMISSAO) VALUES(1,2);

INSERT INTO BREWER.USUARIO_GRUPO (CODIGO_USUARIO,CODIGO_GRUPO) VALUES (
(SELECT codigo FROM BREWER.USUARIO WHERE email = 'admin@brewer.com'),1);
